### ISSUE TITLE
Dataset format?

### ISSUE THREAD

**Issue by joerowelll** [PRBonn/voxblox_pybind#1]
Could you post a link too one of the datasets in the desired format e.g. the cow dataset point cloud with poses.txt

**Comment by joerowelll** [comment]
including config files

**Comment by nachovizzo** [comment]
For the cow dataset 
1. Download the data from https://www.ipb.uni-bonn.de/html/software/vdbfusion/cow_and_lady_dataset.zip
1. For more detailed information on this dataset please check https://github.com/PRBonn/vdbfusion_ros/issues/2
1. For config just check this repo

**Comment by joerowelll** [comment]
Thank you, do you know what the headers of the columns are in the poses.txt ? I assumed it would be position and quaternion, giving 7 values, but this file has 16 per line, and is then reshaped into a 4x4 matrix.

**Comment by nachovizzo** [comment]
You can check how to read the poses here
https://github.com/PRBonn/vdbfusion/blob/0704860c7c9dc0c2899faecd79047cb8c5340bb7/examples/python/datasets/cow.py#L59
